### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [goffalex/week5proj1#1]
It looks like the `<title>` element is outside your `<head`>, [causing some HTML errors](http://validator.w3.org/check?uri=http%3A%2F%2Fweek5proj1.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0). Can you fix this please?

**Comment by goffalex** [comment]
Well that's embarrassing. Should be all fixed now.

**Comment by chrisvfritz** [comment]
:+1: Much better!
